export const PORT = 'http://172.16.10.68:3280';
export default {
    OWNER_SIGNIN: '' + PORT + '/owner/signin',
    OWNER_SIGNUP: '' + PORT + '/owner/signup',
    PROPERTY_LIST: '' + PORT + '/property/list',
    NEAR_BY_HOUSE_LIST: '' + PORT + '/property/nearByHouse',
    ADD_TO_WISHLIST: '' + PORT + '/tenant/addToWishList',
    POST_PROPERTY: '' + PORT + '/owner/addproperty',
    REQUEST_BY_TENANTS: '' + PORT + '/owner/request',
    VIEW_PROPPERTY_OF_OWNER: '' + PORT + '/owner/view_porperty',
    TAKE_SUBSCRIPTION: '' + PORT + '/owner/subscription',
    POST_PROPERTY_DETAILS: '' + PORT + '/owner/propertyDetails',
    SEARCH: '' + PORT + '/tenant/search',
    REMOVE_PROPERTY_OF_OWNER: '' + PORT + '/owner/removePropert yById',
    VIEW_WISHLIST: '' + PORT + '/tenant/viewWishlist',
    SHOW_SUBSCRIPTION: '' + PORT + '/owner/showSubscription',
    CATEGORY_COUNT: '' + PORT + '/property/categoryCount',
    SEND_OTP: '' + PORT + '/tenant/sendOtp',
    HOUSE_REQUEST: '' + PORT + '/tenant/houseRequest',
    REMOVE_PROPERTY_DETAILS: '' + PORT + '/owner/removePropertyDetails',
    DELETE_TENANT_REQUEST: '' + PORT + '/owner/deleteTenantRequest',
    CATEGORY_COUNT: '' + PORT + '/property/categoryCount',
    VIEW_ADMIN: '' + PORT + '/owner/viewAdmin',
    UPDATE_BALANCE: '' + PORT + '/owner/updateBalance',
    EMAIL_SEND: '' + PORT + '/tenant/sendOtp',
    PROPERTY_DETAILS: '' + PORT + 'property/propertyDetails',
    REMOVE_FROM_WISHLIST: '' + PORT + '/tenant/removeFromWishList',
    REQUEST_LIST: '' + PORT + '/tenant/requestList',
    USER_SINGIN: '' + PORT + '/user/createUser',
    SEARCH_WITH_CATEGORY: '' + PORT + '/tenant/searchWithCategory',
    USER_CHECK: '' + PORT + '/user/checkUser',
    USER_SINGIN: '' + PORT + '/user/createUser',
    PROPERTY_DETAILS: '' + PORT + '/property/propertyDetails',
    REMOVE_FROM_WISHLIST: '' + PORT + '/tenant/removeFromWishList',
    REQUEST_LIST: '' + PORT + '/tenant/requestList',
    PROPERTY_BY_FURNISHING: '' + PORT + '/owner/findPropertyByCategory',
    PROPERTY_BY_CATEGORY: '' + PORT + '/owner/findByCategory',
    UPDATE_REQUEST: '' + PORT + '/owner/updateRequest'
}